### ISSUE TITLE
Weak hashing function for ErlangInteger::cached

### ISSUE THREAD

**Issue by point** [appulse-projects/encon-java#11]
The function `ErlangInteger::cached` is used inside string serialization mechanism. But it's internal hashing mechanism is too weak. For instance hash for `ErlangInteger::cached(1273)` and `ErlangInteger::cached(117)` in both cases is equal to `923638`. 

As a result the resulting string which has both symbols with code 1273 and 117 when in `LIST` mode becomes corrupted.

Please fix it or rather change string serialization to use non-cached constructor of `ErlangInteger`

**Comment by xxlabaza** [comment]
You are right...I don't think that there should be a cache at all, but as a quick fix, I have used `java.lang.Integer` cache pattern from Java stdlib. 

Maybe in release 2.0.0, which I am working right now, I will remove it.

The quick fix was tested and build, and a new Encon's version **1.6.6** will be available at MavenCentral in a few hours.

Great thanks for your, @point, issue again! I really appreciate, what you help me make Encon better. 

Thanks a lot.

**Comment by point** [comment]
Thanks for a fix! Gonna check it when it's available at maven.
