### ISSUE TITLE
ErlangPid.cached weak hash funciton

### ISSUE THREAD

**Issue by point** [appulse-projects/encon-java#13]
Starting from some point, the encon library decodes PID's incorrectly and returns previously cached PID instead of creating the new one:

```"ENCON GOT: [\"#PID<0.671.0>\"]```
while
```JInterface got: #Pid<nonode@nohost.896.0>```

896 is the right id of a PID that was sent from Elixir side.

Could you also ditch the caching function while creating atom `return (T) ErlangAtom.cached(type, buffer)` in `ErlangTerm newInstance` function? Just in case.

**Comment by xxlabaza** [comment]
Hi,

It was a premature optimization to make the caches for ErlangPid, ErlangAtom instances. Moreover, it wasn't tested well, and the approach was too naive. 

Right now I removed ErlangPid and ErlangAtom caches at all. A new release **1.6.7** was built, published and will be available in few hours at maven central.

In the next major release, I am going to use atom cache reference index at [distribution header](http://erlang.org/doc/apps/erts/erl_ext_dist.html#distribution_header).

Thanks a lot for your help, @point

**Comment by point** [comment]
@xxlabaza Thanks for the fix. Now everything works great!
