### ISSUE TITLE
:up: netty version

### ISSUE THREAD

**Issue by point** [appulse-projects/encon-java#15]
Hey. 
Is it possible to bump up netty version to the latest one (4.1.34.Final as for now)?

**Comment by xxlabaza** [comment]
Thanks for reminding, that Encon's v1.x.x branch need to keep up-to-date too)
 
Your update is available in a new release - **1.6.9**, it will be available soon at MavenCentral

**Comment by point** [comment]
Works like a charm! 
Thanks a lot.
